pipeline:
  build:
    image: node:alpine
    commands:
      - yarn

  test:
    image: node:alpine
    commands:
      - yarn test

  notify:
    image: plugins/slack
    webhook: <slack_webhook>
    channel: drone
    secrets: [ slack_webhook ]